### ISSUE TITLE
Football statistic project: Implement API data collector

### ISSUE THREAD

**Issue by kilian-student** [demarians/Trainpy#7]
A data colllector gets the desired parameters (keys from OpenLigaDB) and writes the data in a file in the data directory.

**Comment by demarians** [comment]
@kilian-student https://www.api-football.com/documentation-v3
please consider this API

**Comment by kilian-student** [comment]
Instead of an API, I used data scraping from understat.com

**Comment by kilian-student** [comment]
It still would be nice to have a second data source for verification
